### ISSUE TITLE
Calls to helper in helper specs pass and fail at the same time when run with zeus

### ISSUE THREAD

**Issue by waiting-for-dev** [burke/zeus#395]
I'm working with rails 3.2.13 and rspec-rails 2.14.0.

Consider `application_helper.rb`

```
module ApplicationHelper
  def foo
    'bar'
  end
end
```

And `application_helper_spec.rb`:

```
require 'spec_helper'

describe ApplicationHelper do
  describe "#foo" do
    it "outputs 'bar'" do
      expect(helper.foo).to eq 'bar'
    end
  end
end
```

Then, the output of `zeus rspec spec/helpers` is:

```
.

Finished in 0.0076 seconds
1 examples, 0 failures

Randomized with seed 0

F

Failures:

  1) ApplicationHelper#foo outputs 'bar'
     Failure/Error: expect(helper.foo).to eq 'bar'
     NameError:
       undefined local variable or method `helper' for #<RSpec::Core::ExampleGroup::Nested_2::Nested_2:0x000000035478f8>
     # ./spec/helpers/application_helper_spec.rb:5:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 0.00776 seconds
1 examples, 1 failures

Failed examples:

rspec ./spec/helpers/application_helper_spec.rb:5 # ApplicationHelper#foo outputs 'bar'
```

If I run `bundle exec rspec spec/helpers/` everything works fine.
